In [1]:
import numpy as np
a = np.loadtxt('u1.base.txt')

In [2]:
a

array([[  1.00000000e+00,   1.00000000e+00,   5.00000000e+00,
          8.74965758e+08],
       [  1.00000000e+00,   2.00000000e+00,   3.00000000e+00,
          8.76893171e+08],
       [  1.00000000e+00,   3.00000000e+00,   4.00000000e+00,
          8.78542960e+08],
       ..., 
       [  9.43000000e+02,   1.18800000e+03,   3.00000000e+00,
          8.88640250e+08],
       [  9.43000000e+02,   1.22800000e+03,   3.00000000e+00,
          8.88640275e+08],
       [  9.43000000e+02,   1.33000000e+03,   3.00000000e+00,
          8.88692465e+08]])

In [3]:
a.shape

(80000, 4)

In [4]:
a[0:5,:]

array([[  1.00000000e+00,   1.00000000e+00,   5.00000000e+00,
          8.74965758e+08],
       [  1.00000000e+00,   2.00000000e+00,   3.00000000e+00,
          8.76893171e+08],
       [  1.00000000e+00,   3.00000000e+00,   4.00000000e+00,
          8.78542960e+08],
       [  1.00000000e+00,   4.00000000e+00,   3.00000000e+00,
          8.76893119e+08],
       [  1.00000000e+00,   5.00000000e+00,   3.00000000e+00,
          8.89751712e+08]])

In [5]:
#use movie rating
np.amax(a[:,0])

943.0

In [6]:
np.amax(a[:,1])

1682.0

In [8]:
np.amax(a[:,2])

5.0

In [9]:
b = np.zeros((7,1))

In [10]:
b.shape

(7, 1)

In [11]:
b[2]

array([ 0.])

In [12]:
b

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [13]:
c=np.ones(10)

In [15]:
d=c.reshape(1,-1)

In [17]:
e = c.reshape(-1,1)

In [18]:
e.shape

(10, 1)